../../Blue/llc -march=x86 -filetype=obj OmcCfgfile.ll -o OmcCfgfile.o
../../Blue/llc -march=x86 -filetype=obj OmcTarget.ll -o OmcTarget.o
../../Blue/llc -march=x86 -filetype=obj OmcCRuntime.ll -o OmcCRuntime.o
../../Blue/llc -march=x86 -filetype=obj OmcDialog.ll -o OmcDialog.o
../../Blue/llc -march=x86 -filetype=obj OmcHooks.ll -o OmcHooks.o
../../Blue/llc -march=x86 -filetype=obj OmcOdcTextReader.ll -o OmcOdcTextReader.o
../../Blue/llc -march=x86 -filetype=obj OmcExtSource.ll -o OmcExtSource.o
../../Blue/llc -march=x86 -filetype=obj OmcDialogConsole.ll -o OmcDialogConsole.o
../../Blue/llc -march=x86 -filetype=obj OmcRuntimeStd.ll -o OmcRuntimeStd.o
../../Blue/llc -march=x86 -filetype=obj OmcOPM.ll -o OmcOPM.o
../../Blue/llc -march=x86 -filetype=obj OmcOPT.ll -o OmcOPT.o
../../Blue/llc -march=x86 -filetype=obj OmcOPB.ll -o OmcOPB.o
../../Blue/llc -march=x86 -filetype=obj OmcOPU.ll -o OmcOPU.o
../../Blue/llc -march=x86 -filetype=obj OmcOPS.ll -o OmcOPS.o
../../Blue/llc -march=x86 -filetype=obj OmcOPP.ll -o OmcOPP.o
../../Blue/llc -march=x86 -filetype=obj OmcTester.ll -o OmcTester.o
../../Blue/llc -march=x86 -filetype=obj OmcParams.ll -o OmcParams.o
../../Blue/llc -march=x86 -filetype=obj OmcConsole.ll -o OmcConsole.o
../../Blue/llc -march=x86 -filetype=obj OmcDump.ll -o OmcDump.o
../../Blue/llc -march=x86 -filetype=obj OmcShell.ll -o OmcShell.o
../../Blue/llc -march=x86 -filetype=obj OmcLoader.ll -o OmcLoader.o
../../Blue/llc -march=x86 -filetype=obj OmcLoaderRoutines.ll -o OmcLoaderRoutines.o
../../Blue/llc -march=x86 -filetype=obj OmcObjLoader.ll -o OmcObjLoader.o
