../../Blur/llc -march=x86-64 -filetype=obj OmcCfgfile.ll -o OmcCfgfile.o
../../Blur/llc -march=x86-64 -filetype=obj OmcTarget.ll -o OmcTarget.o
../../Blur/llc -march=x86-64 -filetype=obj OmcCRuntime.ll -o OmcCRuntime.o
../../Blur/llc -march=x86-64 -filetype=obj OmcDialog.ll -o OmcDialog.o
../../Blur/llc -march=x86-64 -filetype=obj OmcHooks.ll -o OmcHooks.o
../../Blur/llc -march=x86-64 -filetype=obj OmcTxtSource.ll -o OmcTxtSource.o
../../Blur/llc -march=x86-64 -filetype=obj OmcDialogConsole.ll -o OmcDialogConsole.o
../../Blur/llc -march=x86-64 -filetype=obj OmcRuntimeStd.ll -o OmcRuntimeStd.o
../../Blur/llc -march=x86-64 -filetype=obj OmcOPM.ll -o OmcOPM.o
../../Blur/llc -march=x86-64 -filetype=obj OmcOPT.ll -o OmcOPT.o
../../Blur/llc -march=x86-64 -filetype=obj OmcOPB.ll -o OmcOPB.o
../../Blur/llc -march=x86-64 -filetype=obj OmcOPU.ll -o OmcOPU.o
../../Blur/llc -march=x86-64 -filetype=obj OmcOPS.ll -o OmcOPS.o
../../Blur/llc -march=x86-64 -filetype=obj OmcOPP.ll -o OmcOPP.o
../../Blur/llc -march=x86-64 -filetype=obj OmcParams.ll -o OmcParams.o
../../Blur/llc -march=x86-64 -filetype=obj OmcConsole.ll -o OmcConsole.o
../../Blur/llc -march=x86-64 -filetype=obj OmcDump.ll -o OmcDump.o
../../Blur/llc -march=x86-64 -filetype=obj OmcShell.ll -o OmcShell.o
