llc -march=x86-64 -filetype=obj OmcCfgfile.ll -o OmcCfgfile.o
llc -march=x86-64 -filetype=obj OmcTarget.ll -o OmcTarget.o
llc -march=x86-64 -filetype=obj OmcCRuntime.ll -o OmcCRuntime.o
llc -march=x86-64 -filetype=obj OmcDialog.ll -o OmcDialog.o
llc -march=x86-64 -filetype=obj OmcHooks.ll -o OmcHooks.o
llc -march=x86-64 -filetype=obj OmcOdcTextReader.ll -o OmcOdcTextReader.o
llc -march=x86-64 -filetype=obj OmcTxtSource.ll -o OmcTxtSource.o
llc -march=x86-64 -filetype=obj OmcDialogConsole.ll -o OmcDialogConsole.o
llc -march=x86-64 -filetype=obj OmcRuntimeStd.ll -o OmcRuntimeStd.o
llc -march=x86-64 -filetype=obj OmcOPM.ll -o OmcOPM.o
llc -march=x86-64 -filetype=obj OmcOPT.ll -o OmcOPT.o
llc -march=x86-64 -filetype=obj OmcOPB.ll -o OmcOPB.o
llc -march=x86-64 -filetype=obj OmcOPU.ll -o OmcOPU.o
llc -march=x86-64 -filetype=obj OmcOPS.ll -o OmcOPS.o
llc -march=x86-64 -filetype=obj OmcOPP.ll -o OmcOPP.o
llc -march=x86-64 -filetype=obj OmcParams.ll -o OmcParams.o
llc -march=x86-64 -filetype=obj OmcConsole.ll -o OmcConsole.o
llc -march=x86-64 -filetype=obj OmcDump.ll -o OmcDump.o
llc -march=x86-64 -filetype=obj OmcShell.ll -o OmcShell.o
llc -march=x86-64 -filetype=obj OmcLoader.ll -o OmcLoader.o
llc -march=x86-64 -filetype=obj OmcLoaderRoutines.ll -o OmcLoaderRoutines.o
llc -march=x86-64 -filetype=obj OmcObjLoader.ll -o OmcObjLoader.o
